version: 4.16.3

services:
  server:
    build: /
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: 'jkliop33'
    ports:
      - '3306:3306'
    volumes:
      - todo-db:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=jkliop33 --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 30s
      retries: 10

volumes:
  todo-db:

